[workspace]
members = [
    "demo",
    "call_server",
    "lesson_3",
    "lesson_4",
    "lesson_5",
    "lesson_6",
    "lesson_6_py",
    "lesson_7",
    "lesson_8",
    "lesson_9",
    "lesson_10",
]
